name: Moderator
version: 1.0.0
api: [3.0.0-ALPHA5]
author: Driesboy
main: Driesboy\Main
commands:
  warn:
    permission: rank.moderator
    description: Warn a player that is breaking the rules!
  report:
    description: Report a player that is breaking the rules!
permissions:
  rank.moderator:
    default: op
